#!groovy

pipeline {
    agent any
    stages {
        stage('clean') {
            steps {
                deleteDir()
            }
        }

        stage('pull from GitHub') {
            steps {
                git "https://github.com/tbatty7/simplespringbootapp.git"
            }
        }
        stage('create html file') {
            steps {
                echo "Hello > myFile.html"
            }
        }
        stage('use shell and cmd commands') {
            steps {
                sh 'pwd'
                bat 'dir'
            }
        }
        stage('run microtests') {
            steps {
                sh './gradlew test'
            }
        }
        stage('credential variables') {
	    steps {
	        withCredentials([usernamePassword(credentialsId: 'Example', passwordVariable: 'myPassword', usernameVariable: 'userName')]) {
		    echo userName
		    sh 'echo $myPassword'
                    echo "password is $myPassword"
		}
	    }
	}
    }
    post {
	always {
		echo 'test'	
        }
    }
}
